# Generated by Django 5.2.7 on 2025-10-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_png',
            field=models.ImageField(default=1, help_text=' The recommended size is 700x955 pixels.', upload_to='products/png'),
            preserve_default=False,
        ),
    ]
