# Generated by Django 5.2.7 on 2025-10-09 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_image_png'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='other1',
            new_name='Slice',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='other2',
            new_name='dried',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='other3',
            new_name='powder',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='other4',
            new_name='top',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='other5',
            new_name='whole',
        ),
        migrations.AlterField(
            model_name='product',
            name='image_png',
            field=models.ImageField(blank=True, help_text=' The recommended size is 700x955 pixels.', null=True, upload_to='products/png'),
        ),
    ]
