# Generated by Django 5.2.7 on 2025-10-09 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_other1_product_slice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='section1',
            new_name='health',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='section2',
            new_name='incense',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='section3',
            new_name='non_salt',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='section4',
            new_name='seeds',
        ),
    ]
