# Generated by Django 5.2.7 on 2025-10-11 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_section1_product_health_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='availablesize',
            name='available',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.available'),
        ),
    ]
