# Generated by Django 5.2.7 on 2025-10-21 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_description_ar_product_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='display_title_ar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='display_title_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
