# Generated by Django 5.2.7 on 2025-10-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_display_title_ar_product_display_title_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfeatures',
            name='name_ar',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productfeatures',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
