# Generated by Django 5.2.7 on 2025-10-21 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_whatsapporder_selected_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whatsapporder',
            options={'verbose_name': 'Whatsapp order', 'verbose_name_plural': 'Whatsapp Order'},
        ),
        migrations.AddField(
            model_name='whatsapporder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shipping', 'Shipping'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
